apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- networkpolicy.yaml
- configmap.yaml 
- pdb.yaml 
- service-headless.yaml
- service.yaml 
- serviceaccount.yaml 
- statefulset.yaml 